### ISSUE TITLE
pageviewapi not working on python 3.10

### ISSUE THREAD

**Issue by andres-trrs** [Commonists/pageview-api#7]
raceback (most recent call last):
  File "c:\Users\User\Desktop\universidad\base de datos\INFO133_2022-main\nlp\demo_wikipedia_2.py", line 2, in <module>
    import pageviewapi
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pageviewapi\__init__.py", line 3, in <module>
    from pageviewapi.client import (
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pageviewapi\client.py", line 10, in <module>
    from attrdict import AttrDict
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\attrdict\__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\attrdict\mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py)

**Comment by jagra26** [comment]
I made a fork of [AttrDict](https://github.com/jagra26/AttrDict) with the changes to run in python 3.10.

First, run:

```
pip install git+https://github.com/jagra26/AttrDict.git
``` 
and rerun:

```
pip install pageviewapi
``` 

pageviewapi works fine again.
